#pragma once

// GENERATED by modding/tools/gen_mrf_header.py — do not edit by hand.
// Trimmed from Mesh Rendering Framework's public API header: dropped the
// ENABLE_MENU_FRAMEWORK / SKSEMenuFramework (ImGui OrbitMesh) sections so it
// compiles in a headless SKSE plugin, and added the includes it assumes.
//
// --core-only: also dropped MRF's NPC-composition helper layer
// (GetNpcFaceGenPaths … CreateFromActor) and the Mesh / WholeNpcMesh
// classes. What remains — the IMesh ABI, GetFunction, and every
// IMesh_* soft-bind wrapper — is verbatim upstream text.
#include <d3d11.h>
#include <filesystem>

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdio>
#include <string>
#include <string_view>
#include <utility>
#include <vector>



namespace MeshRenderingFrameworkAPI {

    struct BoneTransform {
        float translation[3]{};
        float rotation[4]{0.0f, 0.0f, 0.0f, 1.0f};
        float scale[3]{1.0f, 1.0f, 1.0f};
    };

    namespace Internal {
        class IMesh {
        public:
            uint64_t id;
            RE::NiMatrix3 rotation;
            RE::NiPoint3 position;
            RE::NiPoint3 boundMin;
            RE::NiPoint3 boundMax;
            float scale = 1;
            uint32_t width;
            uint32_t height;
            ID3D11Texture2D* texture = nullptr;
            ID3D11ShaderResourceView* SRV = nullptr;
            bool saveNextFrame = false;
            bool deleteAfterSave = false;
            const char* savePath = nullptr;
            bool mustUpdate = true;
            bool alwaysUpdate = false;
            float bodyTintColor[3]{1.0f, 1.0f, 1.0f};
            bool useBodyTint = false;
        };

        template <class T>
        T GetFunction(LPCSTR name) {
            static auto meshRenderer = GetModuleHandleW(L"MeshRenderingFramework");
            if (!meshRenderer) {
                return nullptr;
            }
            return reinterpret_cast<T>(GetProcAddress(meshRenderer, name));
        }

        inline IMesh* __stdcall IMesh_CreateByNifPath(const char* nifPath, uint32_t width, uint32_t height) {
            auto function = GetFunction<decltype(&IMesh_CreateByNifPath)>("IMesh_CreateByNifPath");
            if (!function) {
                return nullptr;
            }
            return function(nifPath, width, height);
        }

        inline IMesh* __stdcall IMesh_CreateByNifPathSet(const char* const* basePaths, uint32_t basePathCount, const char* const* attachmentPaths, uint32_t attachmentPathCount, uint32_t width, uint32_t height) {
            auto function = GetFunction<decltype(&IMesh_CreateByNifPathSet)>("IMesh_CreateByNifPathSet");
            if (!function) {
                return nullptr;
            }
            return function(basePaths, basePathCount, attachmentPaths, attachmentPathCount, width, height);
        }

        inline IMesh* __stdcall IMesh_CreateByNiAVObjectList(RE::NiAVObject* const* objects, uint32_t objectCount, uint32_t width, uint32_t height) {
            auto function = GetFunction<decltype(&IMesh_CreateByNiAVObjectList)>("IMesh_CreateByNiAVObjectList");
            if (!function) {
                return nullptr;
            }
            return function(objects, objectCount, width, height);
        }

        inline bool __stdcall IMesh_SetBoneLocalPose(IMesh* mesh, const char* const* boneNames, const std::int16_t* parentIndices, const BoneTransform* transforms, uint32_t transformCount) {
            auto function = GetFunction<decltype(&IMesh_SetBoneLocalPose)>("IMesh_SetBoneLocalPose");
            return function && function(mesh, boneNames, parentIndices, transforms, transformCount);
        }

        inline bool __stdcall IMesh_PlayAnimation(IMesh* mesh, const char* animationPath, const char* skeletonPath, bool loop) {
            auto function = GetFunction<decltype(&IMesh_PlayAnimation)>("IMesh_PlayAnimation");
            return function && function(mesh, animationPath, skeletonPath, loop);
        }

        inline bool __stdcall IMesh_SetFaceMorphSource(IMesh* mesh, RE::Actor* actor) {
            auto function = GetFunction<decltype(&IMesh_SetFaceMorphSource)>("IMesh_SetFaceMorphSource");
            return function && function(mesh, actor);
        }

        inline bool __stdcall IMesh_SetMorph(IMesh* mesh, const char* triPath, const char* morphName, float value) {
            auto function = GetFunction<decltype(&IMesh_SetMorph)>("IMesh_SetMorph");
            return function && function(mesh, triPath, morphName, value);
        }

        inline bool __stdcall IMesh_ClearFaceMorphs(IMesh* mesh) {
            auto function = GetFunction<decltype(&IMesh_ClearFaceMorphs)>("IMesh_ClearFaceMorphs");
            return function && function(mesh);
        }

        inline bool __stdcall IMesh_SetTextureSet(IMesh* mesh, const char* nifPath, const char* const* texturePaths, std::uint32_t texturePathCount, bool modelSpaceNormals, bool includeBodyShape) {
            auto function = GetFunction<decltype(&IMesh_SetTextureSet)>("IMesh_SetTextureSet");
            return function && function(mesh, nifPath, texturePaths, texturePathCount, modelSpaceNormals, includeBodyShape);
        }

        inline void __stdcall IMesh_Delete(IMesh* mesh) {
            auto function = GetFunction<decltype(&IMesh_Delete)>("IMesh_Delete");
            if (!function) {
                return;
            }
            return function(mesh);
        }

        inline IMesh* __stdcall IMesh_Save(IMesh* mesh, const char* filePath) {
            auto function = GetFunction<decltype(&IMesh_Save)>("IMesh_Save");
            if (!function) {
                return nullptr;
            }
            return function(mesh, filePath);
        }
    }
}
