#pragma once

#include <array>
#include <string_view>

// Generated by tools/position-icon-catalog.py from the reviewed private catalog.
namespace SceneTags::Model
{
    inline constexpr std::array<std::string_view, 120> kSelectableIconIds = {
        "sixtynine", "bent-over-table", "carry", "cowgirl",
        "doggy", "embrace", "face-sitting", "footjob",
        "group", "handjob", "kneel", "legsup",
        "lotus", "missionary", "oral", "prone",
        "cowgirl-lean", "solo", "spooning", "standing",
        "titjob", "transition", "wall-behind", "wheelbarrow",
        "pack-x0004-01", "pack-x0004-02", "pack-x0004-03", "pack-x0004-04",
        "pack-x0004-05", "pack-x0004-06", "pack-x0004-07", "pack-x0004-08",
        "pack-x0004-09", "pack-x0004-10", "pack-x0004-11", "pack-x0004-12",
        "pack-x0004-13", "pack-positions-01", "pack-positions-02", "pack-positions-03",
        "pack-positions-04", "pack-positions-05", "pack-positions-06", "pack-positions-07",
        "pack-positions-08", "pack-positions-09", "pack-positions-10", "pack-positions-11",
        "pack-positions-12", "pack-positions-13", "pack-positions-14", "pack-positions-15",
        "pack-positions-16", "pack-positions-17", "pack-positions-18", "pack-positions-19",
        "pack-positions-20", "pack-positions-21", "pack-etsy-01", "pack-etsy-02",
        "pack-etsy-03", "pack-etsy-04", "pack-etsy-05", "pack-etsy-06",
        "pack-etsy-07", "pack-etsy-08", "pack-etsy-09", "pack-etsy-10",
        "pack-etsy-11", "pack-etsy-12", "pack-etsy-13", "pack-etsy-14",
        "pack-etsy-15", "pack-etsy-16", "pack-etsy-17", "pack-etsy-18",
        "pack-etsy-19", "pack-etsy-20", "pack-etsy-21", "pack-etsy-22",
        "pack-etsy-23", "pack-etsy-24", "pack-etsy-25", "pack-etsy-26",
        "pack-etsy-27", "pack-etsy-28", "pack-etsy-29", "pack-etsy-30",
        "pack-etsy-31", "pack-etsy-32", "pack-etsy-33", "pack-etsy-34",
        "pack-etsy-35", "pack-etsy-36", "pack-etsy-37", "pack-etsy-38",
        "pack-etsy-39", "pack-etsy-40", "pack-etsy-41", "pack-etsy-42",
        "pack-etsy-43", "pack-etsy-44", "pack-etsy-45", "pack-etsy-46",
        "pack-etsy-47", "pack-etsy-48", "pack-etsy-49", "pack-etsy-50",
        "pack-etsy-51", "pack-etsy-52", "pack-etsy-53", "pack-etsy-54",
        "pack-etsy-55", "pack-etsy-56", "pack-etsy-57", "pack-etsy-58",
        "pack-etsy-59", "pack-etsy-60", "pack-etsy-61", "pack-etsy-62"
    };
}
